project:
  type: website

website:
  title: "CREST"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: People
      - news.qmd
      - about.qmd
      - research.qmd
      - publications.qmd
      - software.qmd
      - contact.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-expand: true



